# Generated by Django 2.1.7 on 2019-11-05 18:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('cat2', models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('cat3', models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('cat4', models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('mouse', models.IntegerField()),
                ('cat_turn', models.BooleanField()),
                ('status', models.IntegerField(default=0)),
                ('cat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_cat', to=settings.AUTH_USER_MODEL)),
                ('mouse_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_mouse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('target', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
