# Generated by Django 2.1.7 on 2019-11-06 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat2',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat_turn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(default=59),
        ),
        migrations.AlterField(
            model_name='move',
            name='origin',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='move',
            name='target',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
    ]
