# Generated by Django 2.1.7 on 2019-11-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20191106_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
