# Generated by Django 2.1.7 on 2019-11-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_counter_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='count',
            new_name='value',
        ),
    ]
