# Generated by Django 2.1.7 on 2019-12-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0006_auto_20191212_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
